### ISSUE TITLE
v2.0.20-rc.3 sync problem

### ISSUE THREAD

**Issue by gammexane** [FilenCloudDienste/filen-desktop#190] opened 2023-05-11 08:01 UTC
Hello, I know this is a beta version, but jut in case you hadn't fixed this yet.

-Let say I am working on my PC and I have the desktop client v2.0.20-rc.3 opened (I am using Linux, just in case).
-Now, I open Android and I upload a file.
-My PC is synced as expected.
-Now I delete the file i just uploaded from the Android client...
-The desktop client v2.0.20-rc.3 upload the file again. 
-I deleted the file from the web client, eventually I had a sync error in the desktop client. 

Version 2.0.16 is working fine.

**Comment by Dwynr** [comment] 2023-05-11 09:18
I cannot reproduce it using your steps above. Can you reproduce it reliably?

**Comment by gammexane** [comment] 2023-05-11 09:38
Yes, I can reproduce it everytime.
1- Filen Desktop v2.0.20-rc.3 on Linux Fedora 38 opened.
2- Filen Android (Last version).
3- I open the Photo galery in the Android phone (S21 ultra), select a file and "share" it with Filen. The Picture uploads.
4- I check on the PC and the file is synced as expected.
5- I delete the file on Android.
6- In fact, in Filen desktop it says the file was deleted too, but no (check the attach).
7- After a couple of seconds, the file is upload again from the desktop. 
![Screenshot from 2023-05-11 11-33-11](https://github.com/FilenCloudDienste/filen-desktop/assets/509348/5ff8ac9d-8828-4932-8cd9-e611893be06b)

**Comment by gammexane** [comment] 2023-05-11 09:43
Ok, yes, when I delete the picture FROM the Android app, the desktop app detects the change, sync it and it says the file was deleted but no, the file is there... And after a 30 sec or so, the file is uploaded again.

**Comment by gammexane** [comment] 2023-05-11 09:50
Update: I have tested it, like 10 times, 7 times I have the behavior I mentioned, 3 it worked fine... EXACTLY the same procedure, 7 times it fails, 3 times it worked... The thing is, sometime the desktop app, doesn't delete the file when it syncs, no clue why.

**Comment by gammexane** [comment] 2023-05-11 09:53
![Screenshot from 2023-05-11 11-52-08](https://github.com/FilenCloudDienste/filen-desktop/assets/509348/cefc6204-ae4c-43ab-ad11-39d109d6f41e)
See? the log says it was deleted, but the file is still there and after a couple of minutes, it uploads again.

**Comment by Dwynr** [comment] 2023-05-11 10:19
Okay got it. It's only reproducible on Linux machines. Will look for a fix. Thanks for reporting!

**Comment by gammexane** [comment] 2023-05-11 10:43
My pleasure, whatever you need to test on Linux, just let me know.

**Comment by Dwynr** [comment] 2023-05-12 18:57
Should be fixed now.

**Closed by Dwynr** 2023-05-12 18:57 UTC
