### ISSUE TITLE
[Feature request] Flatpak build for Linux

### ISSUE THREAD

**Issue by julianfairfax** [FilenCloudDienste/filen-desktop#23] opened 2021-12-19 15:40 UTC
Filen is a great free and open source cloud storage service, while I don't usually like the concept of AppImages, I think it works with no problems here. However, there's no Flatpak build for Linux , meaning you can have to use the AppImage as your only option. Please include an Flatpak version in your future builds for Linux. Thank you for what you've done with Filen!

**Comment by cwmke** [comment] 2022-01-19 17:01
Hi @julianfairfax. This is a duplicate of issue #9.

**Closed** 2022-01-19 18:18 UTC
