### ISSUE TITLE
[2.0.15] Login issue - Desktop app - Windows 11

### ISSUE THREAD

**Issue by Re4mstr** [FilenCloudDienste/filen-desktop#153] opened 2023-01-19 18:34 UTC
After update to 2.0.15, I no longer can log in.

After input of password, the loading circle spins forever.

**Comment by Dwynr** [comment] 2023-01-19 18:49
Cannot reproduce.

Nothing changed in regards of logging in. If it seems to be loading forever make sure your internet connection to our servers is stable and nothing is blocking it.

**Comment by Re4mstr** [comment] 2023-01-19 22:13
Fresh install of Windows 11.

Reinstalled 2.0.15, still issues.

All the logs I could find after trying to start -> reboot -> trying to start.
[main.log](https://github.com/FilenCloudDienste/filen-desktop/files/10461527/main.log)

**Comment by iiziben** [comment] 2023-01-19 23:58
I have the same issue on macos 12.6.2 (intel).

**Comment by Dwynr** [comment] 2023-01-20 00:41
Should be fixed now. Please download the latest version:

Windows x86_64: https://cdn.filen.io/desktop/release/filen_x64.exe
Windows arm64: https://cdn.filen.io/desktop/release/filen_arm64.exe
MacOS x86_64 (Intel): https://cdn.filen.io/desktop/release/filen_x64.dmg
MacOS arm64 (Apple Silicon): https://cdn.filen.io/desktop/release/filen_arm64.dmg
Linux x86_64: https://cdn.filen.io/desktop/release/filen_x86_64.AppImage
Linux arm64: https://cdn.filen.io/desktop/release/filen_arm64.AppImage

**Comment by iiziben** [comment] 2023-01-20 09:25
Now it's OK, thanks

**Closed** 2023-01-20 15:10 UTC
